### ISSUE TITLE
冠军1.20.1-2.1.6.7版本会导致服务端崩溃

### ISSUE THREAD

**Issue by ghost** [PickAID/Champions#14]
#### Versions (Be specific, do not write "latest"):
* Champions:2.1.6.7
* Forge:1.20.1-47.3.7

#### Observed Behavior:
在服务端mods文件夹加入此模组时会导致服务器直接崩溃
#### Expected Behavior:
它应该不会导致任何问题
#### Steps to Reproduce:
1.在Windows或者Linux上安装forge-1.20.1-47.3.7的服务端
2.从CurseForge下载冠军的1.20.1-2.1.6.7版本
3.放入服务端mods文件夹，启动服务端
...

Crash Log: https://gist.github.com/abc15616545561/74fc90c8b2433743b91f0c311ccf4648

**Comment by M1hono** [comment]
已修复。
