### ISSUE TITLE
Cinder Bullet damage type is NOT registered

### ISSUE THREAD

**Issue by MehVahdJukaar** [PickAID/Champions#16]
No idea how.
Obviously causes crashes when a registry.getKey call is made

![image](https://github.com/user-attachments/assets/0d53c607-d0ca-4e86-b1c4-e56bd1422ca3)

**Comment by Hypocisy** [comment]
![image](https://github.com/user-attachments/assets/35ed429e-695c-4ffb-85f2-1fccebd21914)
My bad, i don't know 1.20.1 need register damage type for Cinder Bullet. now should be fixed.
![image](https://github.com/user-attachments/assets/4132ee1a-aafd-4e39-8311-cf1f94504115)

**Comment by Hypocisy** [comment]
Fixed by https://github.com/CrychicTeam/Champions/pull/17
