### ISSUE TITLE
[Suggestion] Add compat with JADE overlay

### ISSUE THREAD

**Issue by ImAK9** [PickAID/Champions#25]
#### Versions:
* Champions: **champions-neoforge-1.21.1-2.1.8.0-release**

#### Expected Behavior:

* Affixes and tier to be displayed in the JADE overlay (https://www.curseforge.com/minecraft/mc-mods/jade)

**Comment by Hypocisy** [comment]
![image](https://github.com/user-attachments/assets/7b05c9ee-9414-459f-8be3-34118a4b9f11)
Areadly added, but you need config JADE Overlay Pos manully

**Comment by Hypocisy** [comment]
tested works fine.
