### ISSUE TITLE
[Suggestion] Add compat with Mobstacker mod

### ISSUE THREAD

**Issue by BelleBernice** [PickAID/Champions#30]
Hello, i asked the Mobstacker mod dev about compatibility with your mod and he said you can try it from your end :)

[Combability version for the Champions-Unofficial](https://github.com/frikinjay/mob-stacker/issues/1)

**Comment by Hypocisy** [comment]
I don’t know what compatibility you want?

**Comment by Hypocisy** [comment]
Can you please give me that mod’s cf page?
Because they github page have no api or any code about it.
