### ISSUE TITLE
Trying to disable infested affix

### ISSUE THREAD

**Issue by melbellrocks** [PickAID/Champions#40]
#### Versions (Be specific, do not write "latest"):
* Champions:  1.21.1-2.1.8.4-beta+4
* NeoForge: neoforge-21.1.74

I am trying to disable the "infested" affix via config files, but they are still spawning.

I tried setting "enabled = false" for infested in both <instance>/config/champions-affixes.toml and <instance>/defaultconfigs/champions-affixes.toml and confirmed that the changes were still there after I launched.  Is there somewhere else I should be making this change to disable the infested affix?

**Comment by Hypocisy** [comment]
yes, because we recently changed api for registering affix, so some config was not working anymore, we will update it soon.

**Comment by Hypocisy** [comment]
i tested, can not replication this bug, did you deleted old config and try to generate new one?

**Comment by melbellrocks** [comment]
I didn't.  Can you please tell me what all I should delete?

**Comment by melbellrocks** [comment]
Ok I deleted all the config files I could find and it generated new ones and it's working now.  I was able to disable the infested mobs.
