### ISSUE TITLE
1.21.1 Trial Spawners Should Honor championSpawners Setting

### ISSUE THREAD

**Issue by wendall911** [PickAID/Champions#51]
Trial Chamber Spawners still spawn chamions if championSpawners is set to false:

https://github.com/CrychicTeam/Champions/blob/0326e79daad161cd5d1fe1a25a1558eef228e6df/src/main/java/top/theillusivec4/champions/common/capability/AttachmentEventHandler.java#L36

This could be handled by using evt.getSpawnType() and checking if is MobSpawnType.TRIAL_SPAWNER OR MobSpawnType.SPAWNER

The way that evt.getSpawner() is implemented, it only picks up normal spawners. This could be considered a NeoForge oversight. Also, this could be addressed by having an additional setting for Trial Chamber Spawners specifically.

**Comment by M1hono** [comment]
Trai Spawners are not considered before. Thanls for your report. 👍

**Comment by Hypocisy** [comment]
https://github.com/CrychicTeam/Champions/commit/91b846dd4a01912684ecdeb5d2c7d986a6bb99b6
this version need test

**Comment by wendall911** [comment]
Looks good so far. I'll try and spend some time testing this tomorrow.

**Comment by Hypocisy** [comment]
@wendall911 have you tested this?
