### ISSUE TITLE
No affix config generated in latest version

### ISSUE THREAD

**Issue by Saereth** [PickAID/Champions#55]
#### Versions (Be specific, do not write "latest"):
- Champions: champions-neoforge-1.21.1-2.1.8.4-hotfix-2
- NeoForge: 21.1.80

#### Observed Behavior:
- After deleting the configs and letting them regenerate no affix config generated so I cant set blacklists on a per affix basis

#### Expected Behavior:
- I expected the affix file to generate

![image](https://github.com/user-attachments/assets/ff4a14cb-2dd5-436e-8575-b4fdbdc5aced)

Is there some other place we should be blacklisting these now? I'm trying to blacklist infested affix from all mobs

**Comment by Hypocisy** [comment]
Please check the update log
https://www.curseforge.com/minecraft/mc-mods/champions-unofficial/files/5932015

**Comment by Saereth** [comment]
Thanks for the reply, I love that they've migrated over to datapacks, thats great!
