### ISSUE TITLE
/reload returns a NullPointerException

### ISSUE THREAD

**Issue by ArtpokeBr** [PickAID/Champions#56]
#### Versions (Be specific, do not write "latest"):
* Champions: 2.1.8.4-hotfix-2
* NeoForge: 21.1.80

#### Observed Behavior:

- the /reload fails due a Champion's DataPackSync

```
java.lang.NullPointerException
	at java.base/java.util.Objects.requireNonNull(Unknown Source)
	at TRANSFORMER/champions@1.21.1-2.1.8.4-hotfix-2/top.theillusivec4.champions.Champions.onDatapackSync(Champions.java:256)
```

#### Steps to Reproduce:
1. execute the command /reload
2. verify the latest.log
...

Latest Log: https://gist.github.com/ArtpokeBr/66f0ada2b27f9143e55ad25c459edf52.

**Comment by Hypocisy** [comment]
I found the cause of the issue: when using reload, the `OnDatapackSyncEvent` does not have a player object because the event is triggered by a command. If you want to reload the datapack, you can modify the datapack and re-enter the game. I will also release a fixed version to address this problem.

**Comment by Hypocisy** [comment]
> I found the cause of the issue: when using reload, the `OnDatapackSyncEvent` does not have a player object because the event is triggered by a command. If you want to reload the datapack, you can modify the datapack and re-enter the game. I will also release a fixed version to address this problem.

My bad, i found `event.getRelevantPlayers()`, so if player is null, it trigger by command, so send update to all player, otherwise only send update to this player
