### ISSUE TITLE
crash with new version

### ISSUE THREAD

**Issue by VaporeonScripts** [PickAID/Champions#61]
#### Versions (Be specific, do not write "latest"):
* Champions: latest possible (2.1.8.6 beta 3)
* Forge: NeoForge 1.21.1

#### Observed Behavior:
https://mclo.gs/X8KcRE2

#### Expected Behavior:
normal load

#### Steps to Reproduce:
use the latest mod

https://mclo.gs/X8KcRE2

**Comment by Hypocisy** [comment]
Please try to delete default-configs/champions-ranks.toml and configs/champions-ranks.toml, and see if works

**Comment by VaporeonScripts** [comment]
alright.

**Comment by VaporeonScripts** [comment]
fixed
